steps:
  - name: 'ubuntu'
    id: 'Check for tf destroy'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - './check_terraform_destroy.sh'  # Run the check script

  - name: 'hashicorp/terraform:1.7.1'
    args:
      - '-c'
      - |
        terraform init
    id: tf init
    entrypoint: sh

  - name: 'hashicorp/terraform:1.7.1'
    args:
      - '-c'
      - |
        terraform plan
    id: tf plan
    entrypoint: sh

  - name: 'hashicorp/terraform:1.7.1'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" == "main" ] ;then
            terraform apply -input=false -auto-approve
        fi
    id: tf apply
    entrypoint: sh
options:
  logging: CLOUD_LOGGING_ONLY
